### ISSUE TITLE
fetching account balance

### ISSUE THREAD

**Issue by leykun10** [terra-money/terra.js#298] opened 2022-06-02 11:10 UTC
Using terra.js i was able to get an accounts luna balance at the latest block
```const { LCDClient, Coin } =require('@terra-money/terra.js')

// connect to columbus-5 terra classic network
const terra = new LCDClient({
  URL: 'https://columbus-lcd.terra.dev',
  chainID: 'columbus-5',
  isClassic: true  // *set to true to connect terra-classic chain*
});

const main = async ()=>{
	
const balance = await terra.bank.balance('terra13yxhrk08qvdf5zdc9ss5mwsg5sf7zva9xrgwgc');
	
	
console.log(balance[0]);
	
}

```

how do i fetch an accounts balance not only at the latest block but other specific blocks?

**Comment by onuyanik** [comment] 2022-06-02 17:03
Duplicate of #281. You should add height parameter.
```
const balance = await terra.bank.balance(
  "terra13yxhrk08qvdf5zdc9ss5mwsg5sf7zva9xrgwgc",
  { height: 7087530 }
);
```

**Closed** 2022-06-02 20:37 UTC
